// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr1OrHtOkkzEmq4miKpGq18A8DjjvjA9Q',
    appId: '1:488549004817:web:2477fde101c7e502d823b0',
    messagingSenderId: '488549004817',
    projectId: 'design-patterns-c29fd',
    authDomain: 'design-patterns-c29fd.firebaseapp.com',
    databaseURL: 'https://design-patterns-c29fd-default-rtdb.firebaseio.com',
    storageBucket: 'design-patterns-c29fd.firebasestorage.app',
    measurementId: 'G-T5FVCPP08C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0suIyawRb8kuncwZGazkmk3e6pOJKQDg',
    appId: '1:488549004817:android:da08b424861ec340d823b0',
    messagingSenderId: '488549004817',
    projectId: 'design-patterns-c29fd',
    databaseURL: 'https://design-patterns-c29fd-default-rtdb.firebaseio.com',
    storageBucket: 'design-patterns-c29fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBItujHwOhoh6pu7IrJ1q45zsDfiNNVa8k',
    appId: '1:488549004817:ios:14ea3f6afac49088d823b0',
    messagingSenderId: '488549004817',
    projectId: 'design-patterns-c29fd',
    databaseURL: 'https://design-patterns-c29fd-default-rtdb.firebaseio.com',
    storageBucket: 'design-patterns-c29fd.firebasestorage.app',
    iosBundleId: 'com.example.designPatternsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBItujHwOhoh6pu7IrJ1q45zsDfiNNVa8k',
    appId: '1:488549004817:ios:14ea3f6afac49088d823b0',
    messagingSenderId: '488549004817',
    projectId: 'design-patterns-c29fd',
    databaseURL: 'https://design-patterns-c29fd-default-rtdb.firebaseio.com',
    storageBucket: 'design-patterns-c29fd.firebasestorage.app',
    iosBundleId: 'com.example.designPatternsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr1OrHtOkkzEmq4miKpGq18A8DjjvjA9Q',
    appId: '1:488549004817:web:7d2bc76e5ababa84d823b0',
    messagingSenderId: '488549004817',
    projectId: 'design-patterns-c29fd',
    authDomain: 'design-patterns-c29fd.firebaseapp.com',
    databaseURL: 'https://design-patterns-c29fd-default-rtdb.firebaseio.com',
    storageBucket: 'design-patterns-c29fd.firebasestorage.app',
    measurementId: 'G-K6R5TMDRRY',
  );
}
